const lifeChecklist = [
    'Take first steps',
    'Make a friend',
    'Learn to read',
    'Learn to write',
    'Start school',
    'Ride a bike',
    'Get a christmas present',
    'Read a book',
    'Learn a sport',
    'Play an instrument',
    'Learn a new language',
    'Visit a different country',
    'Get a phone',
    'Graduate elementary school',
    'Get a part-time job',
    'Learn to swim',
    'Graduate high school',
    'Learn to cook',
    'Develop a hobby',
    'Drive a car',
    'Travel solo',
    'Graduate college',
    'Hike a mountain',
    'Camp in the woods',
    'Learn to meditate',
    'Ride a plane',
    'Ride a boat',
    'Have a family',
    'Have a kid',
    'Become a grandparent',
    'Plant a tree',
    'Go on a road trip',
    'Ride a hot air balloon',
    'See the northern lights',
    'See snow',
    'See the true night sky',
    'Ride a roller coaster',
    'Earn money',
    'Watch your kid graduate',
    'Watch you kid get taller',
    'Retire'
];
let checked = JSON.parse(localStorage.getItem('checked')) || [];